name: hermes_api
description: >
  Hermes API Integration

publish_to: 'none'

version: 1.0.0

environment:
  sdk: '>=2.12.0 <3.0.0'
dependencies:
  chopper: ^4.0.1
  json_annotation: ^4.5.0
dev_dependencies:
  build_runner: ^2.1.4
  chopper_generator: ^4.0.2
  flutter_test:
    sdk: flutter
  json_serializable: ^6.2.0
  lint: ^1.8.2
  swagger_dart_code_generator: ^2.7.9
