targets:
  $default:
    sources:
      - lib/**
      - swaggers/**
    builders:
      chopper_generator:
        options:
          header: "//Generated code"
      swagger_dart_code_generator:
        options:
          input_folder: "swaggers/"
          output_folder: "lib/swagger/"
          use_inheritance: false
          with_base_url: false
          with_converter: true
          use_default_null_for_lists: false
          build_only_models: false
          separate_models: true
          enums_case_sensitive: false
          ignore_headers: false
          include_if_null: false