workflows:
  ios-staging:
    name: iOS Staging
    max_build_duration: 30
    environment:
      vars:
        APP_STORE_CONNECT_ISSUER_ID: de4a206c-7100-496e-83a5-73e673af6c85
        APP_STORE_CONNECT_KEY_IDENTIFIER: 647N3684PB
        APP_STORE_CONNECT_PRIVATE_KEY: Encrypted(Z0FBQUFBQmloTW1INTI0UjJaSFRmeW5PNU1lRnB0Y2Z2NW5ZcXgyMjUyMFplSWV6ZFJqMWxkNDZBUzlhVnJUcmZPVkcyTHBkVHBuUU9mN1dmVEt0RktoUXVTd2tQc2YwVEpQT1ZVYkFkWGJKdEVVSEpEVFNvRExvelo1UWJHZTRPYmZfMzMtbEw3a0hKd0FjMkxRVFliR0NIazdRM0Rsd3lwcGJHc1BTYWx3MG9FRW5xUnNRa21sNGN6T1NxOU1Md2Y0bklHLVh1eTVXWUlCbmV1ejBQelQzNzRkU2k1NHRwbnRhMEd6UGlGcHFacndlanhnRS04S3V1X29XY3lEd2xWblVfc0xoV1VDei1tWGs5Rkl0X2lXekVSakt2OWgzNWVoSExwM1NxSndmdmctMFRua1JGREdzbjhXVUtXQ190dWxzWlI2b1JOWFZFS1BHZjk3b19hbXh2RlRIOHRmRnQ2YjJmdjZra2RxSFpMT25wa18tYUJuenhKR19maTM0eFZISVhnSHdYSk8tX0ljZE5Rbk9sMVZzcHh0ZG15TmZQcmxxQzYyRk9NNURfWUJYRW55cTN3QT0=)
        CERTIFICATE_PRIVATE_KEY: Encrypted(Z0FBQUFBQmloTW1IMEQ3MkN5Q2RMM0p6cWRJN29xaERvbXVRWlJMUkV3UWJWVFZleGd3UFVpQmgxY0tHSDlDZU9ZNTBINU1qLV8wRmFpOG9UUXhteVpOU2VWMEZFWlF0V1c5d1p2WFVVUmhLZms4U0w0N3dJd0VYMlR6eG5DWjJsX21XN1RzenNyUnJ0WFB0R0dHZHp2ZWNxb1ZaenpQal9KbXY2aHQ1WkIxWmxZM2V3VWYzNDVud2Rkcjlub2IyalpLSm1VZzV0QUcyTElSSVROYTdUelg4M2M1b0NQRHdpOUNqWUNMS0lMUDlJSlpkeGdiTWs5WUptSUZJRXlZSGV1bHptcXZxMEVxS2RvOVR0QVZ2am1zYnFoalhDSW1RMEhNMVJKa0lvemEtYXN3ZjdpTG1MWkREREJyQnZhZHVVWDVwRTloS2ZhSkYwX2c2YXd2ZmtrUkx4N2tVT243b09sWVphTmpsM0hCa01OcmVFV01QYjhHS0FyX01LSk5jRXVfTF9Nc2dUVmhDbXM1MmJjc0xMVjRMVS1WUjR4VDU1SnF6dkJQZ25jUUpmUjhONTUtWU9NUHk3UDhCTWxKS0tLMmJJbndhdlpKbUJSYmE5eS1YYXR6NlpRQ2NFX01aemttS3lmNjlYc1pyQmFCNGdaUVVpdmdDOGdtZUVBZEYzUC1PNVVYSWlRdlEzVk9BanFmM2RseDhmRDZya3hhOHdUdm5BVy13d083aHdqNlpaMXJoQ3ZwaDRkSHVnZ0VEbXlCbDFQd2thNmFwUHRqcHhGbDVoQUNWYkRoYzdmcDdhVGduYmZBQkptN3RNeHp5S2VFbUMtQ3M5Nm1XejVlNTBJTHp2SThINkZqNGFoT2NtXzB0QmF3VE1DLTB1cThpVWJIZTRCeGRYeGV1X0FQb1d2MkV4UlVFMjFJVkV3UkZlQ2hSa1F1OHRXa0QtdU5aaDBBQXNtZm42TzRWZ3BfY29zVktHOHdvdkJ2WUFubk1WaHZkUjFWSzlGMEwySzdURUxtNkhIRzVhWURSbXFSdlVSSFdaZEVoZzZFbkNOcGxzc1RsSGN1SGkyYml4RVdEa2FCeDBqZmdrU1BYaEl4bjBVNHA1aTZReFIwbnRZa0Jlc19wekRxZFdMV2ZnLXNLS1Z4dGlUM1pyZ0MxWnQtVEgzb0tpS2JtXzdteC1LZm9kSHE3TGlYUGQtaEhUUEdqc2Q0aXJmT1E1bTVVRjQwOE9rcUJOZlRNdHJ2aEVtRWNtUjNCMERZdndKcEpJdjlCU2xRaXNhYnU3R3p0LUxpakJsdHI4WEY2OWRSV1BhSDZnTkFwUDJOVGktb3lseXVsUWxUT2lXRnVIMlBPcHVoU2M5cmRINTUweVR1ZVpoTHFfenBPbUpvMkEtdnVBQ0EteVR1QVFGZjhYSFowNnVvSHNmZnFBalpZbU12TVBDT3BCR2xTdjRNNHhIQWsxb2ZmYmF2LTJXWHJ5eGc1dTJ1dmJoaUJmcW1KUlE4WUhuZGVIM1Z6Y3diRm4zNm10Y1dnRDMxYm5GekdXcm5hbnRUTjRvd0hwSHY2Z2lxVnlCSHcxT1NZZDlvVVIySS1sVGJSaEZFTEpWN1hnTDJQcXFRam9NZDFyMU1LSHprMEpFOFpUaVdhR2huVnoweUg4N2ZLbnZITnJCZVNqaGdCQkJVZlpSSXhRdU13OVZURWxGSkdnUEpYNGt2MUJRSmdLWUJGRWVQNlNLckFzdS1CbEtpbWpvaGNoTm1YTllKUUZZaVlWdEcwZURRbEl4RG1FVE9IRmVGZzRJOUpmaGFmZ0tXVVhrOE9ET2hyTGlsUEZBeHN5ZXluX285RnJWNklDb3UtM2VFbTF6c2wtRXhEU3U3QmE5SHR1QmdOOFcxSWdPeF9tTDJSa3pqWENVR0QtSHdUT0EtdUhPc1hKNzk5RS16dG1taVV0VnZkRHVrY05BU0JKT1YwZ3lOUXBHazBFTnBJSm9LNlhwT3p6ZlBCRjROSUJZYldMbVVSWHZxT01nYVZKd0pIRWc0ZTR3eEpOampFeHc4TGlGU1EzRUt3RVU2SE83R19MX2ZzWmhEOEZncGQyOEZsLW9wTk1GSWdsZlF5SFhqWlJtb0xURGdXYkRJZ25rV2ZuTnlxa1lQYk01RzZQQ3hiU0tTd3pnRXY3SjFlNDNxSm5iQzRwU2ZzYjRYVm1jdEhSQkItVHlHakJtTEFmUi1MMm5XSnhhZjhCZy1rQzFJQTVhZzFRc291clRiNk8zYlVsUDB1WXlQemc2cHlvUi1vV21qempxbWpGVVdqbHVKWERXeFhEbkhqZEhaVkhkQm5XdTh0ZTZvM0pRbHlhVEplaTZWb2xsUnlDUU9qQ0Z6MVM4UkFGenR5cHM3cXpjeWhVeW0xeVR0c1J5TUZuOC1SSXpJbDRaRVdvRGlOUFJmTjBCaVhEbkp1eExmdGJYZExleEREN3N1bVBkanFBT2pwdlZ0Qjk3aFA2Vk1EWFd5MGIwc1dTN1V3bmtDMzVVdEJkTDFDcS1tLWRfZmtlY0laYmJua09CR2x1b0MxZU5PWjZDOGR3TEJMNGtPMDJqN3dOT1lIRzREaUxsUDNfWkpMRUw0am9CMUlMS0xvUExaSzNHb3lXbDQ1T2taR050NHhSNFAwUDB4aTBxNWJXRWRlV3N5ZExUbmIyZ0lWVXVaNmxBdjg3a1l5dWZpNTVMQTFucWxIRUNaNkpNVzNWNzBnVUl0TlpuTVBxeURJTnZpbFRfR1l3aDZqUTRwWmpEX1FDclhqdGlNaHRWRGRMTGFsUzJIMEZTdHo0MDh0N1RNR0lkdlZWVUdrbnZSanRXTWpQZVpDbUhaUkFTUkppSjN1b3k4a3AyQVdQRG9JZEpidG9XRmVPMUowbzJOX0JJSV83SWVDa2VYX1c3dGpuX3RxMHNMZ1hFMndMQ0p2MVpCX05Zbm4xNVVoODlQdkw4R1dMbFV3VXBnQU5kbTVLaGdaZF9zWDV5MDNTUE1waWd6WFlfal9PcWs2cFVXN0dMVkNxejhKeFpqZW1YTTFXZjZQWnRval9NX19oLVZIQkJwYUVQZFRidndB)
      flutter: 2.10.5
      xcode: latest
      cocoapods: default
    cache:
      cache_paths:
        - $HOME/Library/Caches/CocoaPods
        - $FLUTTER_ROOT/.pub-cache
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: staging
          include: true
          source: true
      tag_patterns:
        - pattern: '*'
          include: true
    scripts:
      - flutter packages pub get
      - find . -name "Podfile" -execdir pod install \;
      - keychain initialize
      - app-store-connect fetch-signing-files "tech.getcrunch.crunch.stg" --type IOS_APP_ADHOC
        --create
      - keychain add-certificates
      - xcode-project use-profiles
      - flutter build ipa --flavor staging -t lib/main_staging.dart --export-options-plist=/Users/builder/export_options.plist  
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - '*.snap'
      - build/windows/**/*.msix
      - flutter_drive.log
    publishing:
      slack:
        channel: '#codemagic-pipeline'
        notify_on_build_start: false
      firebase:
        firebase_token: Encrypted(Z0FBQUFBQmloTW1IbU5MTUcyaVVmOUx6SUpkNzhJc2JuazJnemRsZ0U0X3ZsdHRXUWJ1THFDbktEMWVCOUN0dDlacm11cWpnOW5zaHBHUGttN3JvaUdrUzNQMGI0ejRQRW0yMmFiOGRMTzR2UUsxdmdLSzBqeVE4TlJLc0FZZVhUaUllTGF2dVFSWVFVdlc2YXI5Wld5VXpJcFo0MlhGNjJVYnptYjdYQklUa2l2WVJwd041R3RDaWtHRjNLM1NPanBhSEJWUjhBWGJKWS1SRUoxai1nNlNvblJmb25zb205dz09)
        ios:
          app_id: 1:899655281519:ios:451eeeb0d4ae1dff77569a
          groups:
            - ios
  ios-production:
    name: iOS Production
    max_build_duration: 60
    environment:
      vars:
        APP_STORE_CONNECT_ISSUER_ID: de4a206c-7100-496e-83a5-73e673af6c85
        APP_STORE_CONNECT_KEY_IDENTIFIER: 647N3684PB
        APP_STORE_CONNECT_PRIVATE_KEY: Encrypted(Z0FBQUFBQmloTW1JU0JLV0EtMWMzaHNqN1NsX1ZkTnR1UVJ4QWVtSHR5Wm5iUlhnZ3d3a2JVODgwVS0wRzMwVmYwVXBYLUhsVUliZ2s2VkstZUdDcmJJNXdkWThjel9ZMzN1UWt5bkpVTG1xejdyMG1YUHd4bmJ0Ti1Fb0c5VWJucG9RcGs5aUtaQUlsN2NoalZFeDhIeDlCalNhTV9mQkhmY2RSbGhsSzJuVEF1dDY5Ymx1YkJRT0tCWnEwbUpmanJkUlp6aGNyZHVXbk8xUEFJUkpxVzRmanU5d0tSQU9KTXp4enFNQlJQNjlIdkcxZXV5OVhsMm5QejZCak0yLS1zSWlLUXhsem5IaVBPai1abUdsajJlRzlTaWFrSnZCeWllZ2JLekh0MS0wWnZyZC1BTmdEZGR1cm9odTItY3lDZ1dLSHRJWFM1SVcxaGN0TXVKalVuc2ZucVdKeHVCVjUtbFM0Q19SbWYwX1ZLdDFkQjlkWVdMUVJvY1EyYzNaS2Nua0p1QktJanhhLXFQT0tOSnNlbFZpVGdheTcwQ2NMZHB0dk5RV2F3RkgwODhLaVNQNTQ5QT0=)
        CERTIFICATE_PRIVATE_KEY: Encrypted(Z0FBQUFBQmloTW1ITmJfRks0S2c3TWM3eE9CSnhzNGlIWUd4NUJGdTZIcGN2SXM4M0V4Vm5jNDNRUEVLMnpnUTdqSW9LM2szUWY0TTdtZTZIZGdKN1FqOU1BUVFRUldJWnFSdnpnWnQtTnVCRHhuMGprRHBHaUJnckpHVC0za3RGZm1nX2xidXR0UVQtXzdXd3VOX0w3SXMxUFVmb19zZ3pOdlNiX0MzVU1BZy05Y2owRGl5dEJrX3ZOX210SzVMbVl3UTlVRG03MEFpSEkwVFpkMEZfbmRyRUtlQ09TLVdQZ1ZmcjRUY0M4YVFmeHBmTDkta0t0N1JOVHV0cHJjZzlRUVFtajlXTTREdElxSGVDa1FrM3B5SWhCRmdTZjV2OFlnS29iYWFzVlhMMkFsWEtxZW1zZjlfNi1JcmpXSDBfUXRFM1RHY2hJbW5YSkxMVmtUcmFzS0c0ZVJFaXVES2dLRURZTF9YZzBqNjJJM0l5N1pKXzlYbUMyclpKZENvb3RwUjhXeGk5NmtlcmgyVFhwVFZSaHhKU2VXQ0hlWmE1UERzaFdXUENTMm1US2Q3WjR5WXBRZ091bWtOR1dnMGFZTE1WT1JRRHE2Z1d5LWlFOHVITENuem04WG5kN1RETjU5SlZ2SW1aQlhwOG5tek1oV2ZMSnhIM3IxejcxdkxSV3V0d0pIQW1rVl93UjhaNG1Bdk9CY01nYlNzR241YXZwU0F3NzN6b3c2T0NqOFhya09welFMSE9Wa2hIUkZNR3VfcnVzbkozTjB6TzBnV3FNUlNSVFI3ZzRzV0J0OVF1aUhEREJTUGtkTGNvRnhVR2VtUkkzcXV5aTh3M29OLVkyTk9Pd2MzZXlwQVVIZUFzNlk4c196SXdCVElnejNZY3hqZ2d5bHhxZU05Ti1FR0Y3XzdhdDFwUnVONm1Ha0N0NDZRZUd2WEFoVHppek42dmxGS2RsRlo4cUo0bENDY1Y5RzBmMERlT2RJX3JyaF8wQkIyMkkybnZBb3J3ZnN1LXlZMFoxQ2Z5S0hDa2kwZnQwWVlFdWJVYTlqbHYyRFpqVm1iRzhNdWtJaW13MC1KZXJrdXh5QXRheUlyMHF1RXlDdEV2SUkxdDlvc1U5Umx6WktKVTdrUTBXazZxdGxUNEdTSG9qRElHTzRWb2RMQnZEdkNoNkJyQTNtX2x4MnBycGhYc2FISU1DT2RkOVh1aG9lLWtJUldSRnN1NVVDZHFyR2V3cnpQcG1FT2hXRnhCRWlIMUpYT0pmbVZZeGg3ejVwbC0yN2JZNXhoZmM0Z2VzRExRN1VoQUQtTWhQQk9Vc2RyVjNLVWVYekdfUmNRdlNqbS1kRGNhZTJKbWhzUmw5THprQ3VQblBNaWg4YTRQeW81Nll2bUczTUtvSWY1R3RqT09HVFhka1lkM3pncFNndGw1bU90Z3RHeXZkSzNIMzhBSkdfaGpNVDhFdGpQWWlRblRpYVF0Wlh2aU9kaUJMaUF0RzMzWjBtMGtQODlFTmdqbm5raGtSbzBDWTdKNnd4dWtxYlFyY0Z6cVJLdkp6TGZHWlZPYy1aYm5BMHJnVTdybVpmZW1IckNVWHh4OTV4LXRCOEpZMGhCRmFydDFYaFVnbG1vSEtYT3VGVkE2SHhubHZxOGRCQ0t5VDZua1p6eHR5Y3REb0JjVGgwZzcxWHVoNEF2cTY3ZEZwSGhLbTh0bTRscjFsYnd1OHB0Uk9YdC1neEtoLUZYWWVWTUR5LWsxS0dhcnJBdXkzamF5MTV4REtoNXhueDlzdEdiWW1aejJYMTVMRkZXYUdtSlVpdHUxZDhFTV9IeFEtRnp6QUgzT0tLNTRHUjhJSDV6UDN1d0xfTTJHakZhX1l6enAtOUhpWlVOQlE4TC00S3N3MF9oRmR6ZktFa0g0dGt6djNGcy1XRU81TmY2cFlraVdqMUlENEFMVnU2OEFMZ3kzUktiVEtKTG84T0pyODVlb1hkRnZyUHd2bC1WN3psRjFNd2kxSnFVNEZTSXlGSndjaHJQQnYwcHhzaHo3Rjl3Uk1xam8wdHZCTjVRa1B1OWFhNVdfVUlwclEyTFJRdFE1b2RyTFVUU0RwNkpSZkhiZmFLeDR5Rjhha051RkowUnJoNXFUV3F1LUM0X2VOdUhRbEF4WnN1YzJRalNLeWhvdkVVb1ZPMU83VGlXVXBnUFlVSU9RSzBiZHhKNlBGMEN6LUN1ZGUxRWo2MEIyNUUzYzBhNEh4enZCeHVsQ3p6MU1HcVJKZ0xxSUVYWVJtS1V5elRDMGdsaVh2M1V6MDJ1WkpMa1NEbWo3Z0E5RzZfUFU5bW9OcXFPYlFVc2RSdGlHQnBZMXJ2bkZsbm9IT3Axd2FVQWZCRl9kRXJMOGJSTTlzbjFnRy1kcXNsNURuNi1zYWtIcEFxUU95VVV6Y0w2aW0yME96U1ZNdzhYQ1lNM21QUW9HR2VoTV9OUWJCMnJKVDlyMUxlSlJ3bHJaLVBVYWZ0UE8zR1c0QzNHNmlWeXJOS0plUVZfUEducEJib01yT3dFdFhncjM0Mi1rcnFMWFhTRGhSVHRYeWVTUU9KQVc3UEZoRDR6ZExwNV9INVZKTmRkNzBvb2RzNGVfUy0yT3lxeURQNFdJR25ObjdkS0dTNUZjMUdKbFV5blhEUG9kcFpCY3pHSHpxdm1NSDNXUkttM2FBbDNIVGExRFdyRm5wRlRBa0Q0ZFVTTEE5dUxwVUFzamFyb3BiYVJYb2V2N0pMV2xrbjdhSDdhMDhXaXZEVV93bm12cVJ0OXMzMjJZaDhyVjk0YnMxVFNuTFdhcXJndThSMV9iOGhJWTA3Z09TTDUxeDNWSkNXUjZNTHpYTVN3TExVcnUwTXdaNlF2SGYxV3pSa203THUyLWNnNjlKdWZMY0JiVU1oS3N3RFR5cDRHdVlGeXJRWHhSMms0X1RQNmJBNVBaeDBRZjlmYjBYYS04YW1lQnlLcU9hT1VxTm5scXN2R3FOX2RYbjNYV3ZHUUhMclhscjk4cTRPVEpLckZmT3A2YzlSR21obzRpZ0k0REJpYzVZSTE1cDJmUVdHYm4xcFc5MWp6)
      flutter: 2.10.5
      xcode: latest
      cocoapods: default
    cache:
      cache_paths:
        - $HOME/Library/Caches/CocoaPods
        - $FLUTTER_ROOT/.pub-cache
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: main
          include: true
          source: true
      tag_patterns:
        - pattern: '*'
          include: true
    scripts:
      - flutter packages pub get
      - find . -name "Podfile" -execdir pod install \;
      - keychain initialize
      - app-store-connect fetch-signing-files "tech.getcrunch.crunch" --type IOS_APP_STORE
        --create
      - keychain add-certificates
      - xcode-project use-profiles
      - flutter build ipa --flavor production -t lib/main_production.dart
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - '*.snap'
      - build/windows/**/*.msix
      - flutter_drive.log
    publishing:
      email:
        recipients:
          - joel@getcrunch.tech
      slack:
        channel: '#codemagic-pipeline'
        notify_on_build_start: false
      app_store_connect:
        api_key: Encrypted(Z0FBQUFBQmloTW1Jc19wQlZvZDZhWkFHb0o1VnVpSzV2RVctQUFaRnFYQjhXdmZadTRPaVFudDRFbFQ5c08tUzJRNExWeUJzek4tNC01RWd5dWhXLXVEMHE2OUk5cnVsTS0wcHo2N29NLUVCR3FmOHJhWGFJVEpXczlteVhuRV9QVkVyOG1BWW1rdlJqdmUwVUVveGd1Z0gzRnprUV9ZdzVJbnkwQldOT3JxY2VucW5TT1VJU0liSlJ3SUxvblE0SHJxb0pGdkJwQXZ1anh4ZlBNQUdvZnBpX1BvMTN4eXg2d2pmd0lHMENmQUotV2ZJc0RpR1U2TnN2WDZyZjdocGdaMlUtaHdDVVJxM3pSRmc2VUNLQ1pYMW1OemNQTTlvcV9QTnNJbnFZQVVTd2lHYnlPdjY0SXNfQlY2MHU2NTU3MjRHOGZZVlJQNmpYQmVIUUdzVkZsb1g4OUJhUmMteDRTd2hQM3BaR254QXlvMERZWlF3djlieE1DcXAtNVduYUlGcFZ0ZktFYi1LemdDRkkyYm9pLVFVS0RpbEhPVTgzc2U3b09DcGw2WEVKZk9tTUlEamtlcz0=)
        key_id: 647N3684PB
        issuer_id: de4a206c-7100-496e-83a5-73e673af6c85
        submit_to_testflight: true
        submit_to_app_store: false
  android-production:
    name: Android Production
    max_build_duration: 30
    environment:
      vars:
        ANDROID_KEYS_SECRET_PASSPHRASE: Encrypted(Z0FBQUFBQmloT05KY3Rsa2ZibHhKd2ZQQlp2Uk5UajdtNG9vSXZTZl9TLXp5OU12RklRMUpOZ1paR2dUWGczTFFhazNoNnZNRXktUFZCR0x4Y2NXcE9PUE12eWh5TVhxbk93bUFXVml1Tno2ZXFiRGRaaTRBMGc9)
      flutter: 2.10.5
      xcode: latest
      cocoapods: default
    cache:
      cache_paths:
        - $HOME/.gradle/caches
        - $FLUTTER_ROOT/.pub-cache
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: main
          include: true
          source: true
      tag_patterns:
        - pattern: '*'
          include: true
    scripts:
      - brew install gnupg
      - sh $FCI_BUILD_DIR/scripts/decrypt_android_signing.sh  
      - |
        # set up local properties
        echo "flutter.sdk=$HOME/programs/flutter" > "$FCI_BUILD_DIR/android/local.properties"
      - flutter packages pub get
      - flutter build appbundle --release --flavor production -t lib/main_production.dart
    artifacts:
      - build/**/outputs/apk/**/*.apk
      - build/**/outputs/bundle/**/*.aab
      - build/**/outputs/**/mapping.txt
      - '*.snap'
      - build/windows/**/*.msix
      - flutter_drive.log
    publishing:
      slack:
        channel: '#codemagic-pipeline'
        notify_on_build_start: false
      google_play:
        credentials: Encrypted(Z0FBQUFBQmloTW1Jdm9GZUZiU09VV1dUazVNQThCS29Lb1V0bzl4TllBSnZwcWd0QURFUmJGRlRhbExOaWJGYU1GV0s3U04wbHp2LVBwcmw4UDZIdmZPd3lPSW9DYmJlR2JkZ1lwcnI2R3l2MzlXVWVRRUwyLUQ2VG0yNWxMYnExT0c3QjNvWVBkZUJsSE5YR211WGI0WHZJcno4S1JlMVAtTlpydjhnTXh3VUNHMzdMc2tKRE96TWwwMDR0TmQwY192eVZUMTNZeHhZclpPelF4OW53c3JmWVN5SWdoNXRadnNLZS0zQWtPRFJPX1lUNE9PYkV1T1hEM0pUVk1tOExBX054cmdWUVpDbEM0RnFweTFMY2xhSUJuNGRWcVhaazQ4ZEdTdzJnN2o2VWRydjhlR1Q0VF83N3hXek1QamV1dmpOdThWYjY5UmVQcEJ4YkVKQkNQQWlBdjZPVzZuWDZoWV9aUncyVW43ZWViYkVuRC1kNWZEbU9lZlVUUWpZSlNtMTFFVVdkQUtNajd5eTRGWTV6Y2tzTUt3dTY3aXlvRkRTUXkzUmN3Smt4eDhYdXo3dkRKM0hlU2lPbTBWNllOaGhsZUtQdFJZVkt0VHF1WjhRVXJObGdVR0VYOUF6U1NacmUxS3g5MVBuTHBPRTVBdmxaWnVvdDB6U0JEZ0NzUlpYSWotaEJhQ0UyeXhEb0J5WTVENGVGUVpwOHBKSXhQd09IUjZFVFRBbHZZbHItZkVuTmNHbXNNaFV0U2ZtaU9PQ3MwYUZnUTd4c21DdERFU0NwU242SzF4VmwwX0pVQlJ5dGI5X1RTdy1IbkhnR1NLWEdleDZQTlY2N1QxTlozTWRKeVlZeUpaUmhRQ1YyNUE3UGJDX2xza3ZXbWxneXQyV3JkblZQNzVfV1dCMVE0MFdKRzFnX284RHd6X1V1bzFpQUZfM3hhQ2tMYjZBRTVCSjNBeDMtUkg3bVQwUDhEWEp0OW1kZUVsVTNEV2RFSThsQ1N1WlJ5YU5Fb3FkWXlKT2Yzb3QwMmFmTnl6UEpqUEt4dXdpT1lfOHNLQTQ2LWRES2YwRktWcjZ5MXhuUmhNek1aUWROdmlITG8zZWpFR0U3ZEhaZDQxVjJhYVVDbWJSS00tb3U2U3ZnUjBUT1YyVU5tMGJYbzRtbkp4UEVEMXRBbF9Fc0kzeUZWZzhjcW5kYXJ4cGhrZ21vRFhvOXlGODY3M0NFTENjOFp2Y2VRMUpvdWdDSkpybXUxaXZULXFudFZhQlNaMmxLS3FPX2RFWF9xVkZsTUZRc2V2eHhrRWtGWFlSLU5LYXNidWdlZ016X2VQV3AtdGNCNHJndktNRjVxSTJyRkZreWdqYkgtM3EwaTQ1cl9aQVpiUTRReDBqSENrM3hVM0ljUTNFVHJLSi0wY0NJYkZaVWt6ZW5Ic0prbm4wb2FkRzJRYkpqMjZJMHdJekIxanpUVlQwQ2RYNzFGamRlS0tTQlpTY25Qd2FJdzZvbnJtTzdxNlRwZVFtVjkxSUlNOW5aNnpTeVRJaVdVbnNBOTJYM3F3RkVoZE93a1ctbENxeld2LXhleFNEX1BOV01DYmRlUTd6RFRpalIwOXFid0Z1eWNRUmNVVUdFdTAxVmNicmsxdWpCajRKUEdzSWNXMVU4YzFpLTJCQzQ3V0pYRlp2bUF6MFVRU1VCZXZKeGhIa3FUQUdGczJWRW9LYVJTWW40U2hoeEJLNi1nblF0QWQ2NlJ2Q3hiV01DOHBfRGlvUmdHZkQ5TWdtTDZSRjd3eGNZTUpGRndSVHlhOEZxdkwwVFhaMEVpb1BoekhhcDRlSkFncnR5TjlvRkNDeGRBWGZha0JiSlRKd0F4b2tIQXlXcEtNanlORUxYSW9LUnVTMkZZYlF3N0I3NkoxcnhFTlIybVJVU2tYWmN5UTBOazBzOFlKNGVfUUhQVXQ2QWF3N2I1cmJZYjZpSTZha1p1SkN4MGhySDZWbEtiNEFncW9pUVRGMWdKclk2ekdPWUk2eDBqZFBNQ3ZPZWNiQWxKbkpXZWIxbWFFcVRZazZ1NVVzUzViUG1lVWk2YmRQUDlmSHpSVXE2MzU0eGNEYThtb1BzYTZYdmVJeFl3LU5VMjMwazNqVENWTFRXTTJtQlo0ZENpa3ZzM1VkMFJ4anVVVTlXTXhCVTQzQzBVNmJqSW1mQ1pUVWFRbHhlRlBXWUpuMWczSWJ1Rk5ScVV3ZDBvbDRod3puNjhrSHRPTGNzbGF4U0QzNEd0WTVrQ21mZzVzQW9qNGhWc1d0eTRXMDBXeFd6UkNNV050LTZTWkw3Y1NhWHUxd3JPWnVrODRQaHc1SWgxSUxKYjNOOHNxdzZLTWxkRVJiVkZLMXVvcVhzVVh6Y1JnWkdsU1lGS3JjMjFJU2ttUXFtQlU4amlHcEd1azU1Z2p2R0tTZkM2SjB3WFE4YjlwSGhOazRJNGtBNFhxVXAxcWlEcG53T0xpdXppZWd6d1h2M1d2T0ZNdVBaSC13UURUblF1bEQ1djZ0UzdXVFpJUVZhUDRBZEJhREpfNWdDUUVncEtuZ2hHdU82Sm1pZERBejlTMzYxSzY2SmsxMzAySHRMX2ZtSjF4Um5ndDlDZWlJQUJmVWZNMlpaTU1wYkNhOS0yQ3FLZkpVUXp2SUtjQjA3YThyNW9qSnZRTkVCNm9ZTFpIcHlhREtsNGJDVGM3bDdDZnd4X3pOb2JqR3AyZ1NOeVpqa1pXdUEtbWZLcGdTWS0zcW9MWXFESm5tc09NN042RU1OVjQ5ZU9ES2k1ckhyOWw2YW1nZUYtTDdlaUZOYjFFcmplQk45UDhlVGFNNzNTYW45NzhTakxvOGwwYndKNFFoRUstOWpIM1RfQlZNM2FBb2VTU3VaZHZ4TnExOWdmeHg0ZkR0WElIMk5Qd2gycjVKZ3BPUjJOczFEa0xyUm5KRlM1dk85VHFWWXZhM3RRS0puenVrdV9QRWVYWlhwUzZWYTA1TDdBLVNNeHdOc0hldmlUd1VrOFVmU3BHWmlnb2h0VGtMNGtoeWlOa0V3MWpmQUJNV1NQMG9obGJ3cTc2UGVBQVdDbXBlSE11UlMxSmJ6TG9vSFRWUXRsYU1YbUNDZHhIM3NkaGpLbzk3Mkl6VDJTdFpEZnFOUFF3eENJZkR6VVkyY3MtSjJrNWVFLXYzQ0M4WTRwa3RsSUNYODVOR2VoYXhIV29HenppQ2dWVkRlbG55a0o4MnFUYnZiTkxEWEFySTc5TVhubExfRkdjQ2NRVzdXNW1SaGZUc08xc0hpY0MxRUVXX05WS3R6YVFLUVA0WjNHeHFaUTc3cUZvSTVKcGdmMVZoa1dkRUlNRy1EVU96Vmc2QjN1MWJLWGo3eVYzTmxTZEhESmZSenZvYW9STGNfTTltc1lzVEN5OUN6YTNCR2RDcE9sTzUxdTBHTWE5Vm9PSkZJeWppU1FzWUN1Q2Q0SXExZ2VEZkpHeEtSQUU1UUtkZVVseE9TRk05Ynhhand4OFNGcDFNQ3BLd2g5Y3NNeHpybXF4eURlQnEzVERaOEdPREd1bWp3WmpHbmRtMlBfeVQ5YlJaSFdYUzJhYXhSV3dnSU11cGlHMEVIRUg2UXN6dVh2MGNOSWhKbTNOVktBV0UtWjYyczVwemRhZEVSa3hEbUtEOUNTb0Jfdkt4allqR1V1YmRrSkN4clNqMElLTzBXazJTSnFHUnp6WGNNd0k2enRjRHVPX0lyRlIzb0ZDWEdvMXVHT2NhV3pkVklBbE9jR3M2M0lWdTBSa09zZGpHRkQ3N0NxZi1hNXZZOThmUWlYQ2ZnNjZPREswNFgwWVJRZ1NCa2w4ZzgtWHNLTjBrWC1fV0doTDNnM0NfSmZJZ0w3bnQ3TEZ2Qkk3NlZFZlp6M0FGc0RhbkU5b0gwdDZqX2c0MnBPNW9NV2dzM0R5THlhb3JmN2F5TXNYaWhrYThkempZUW1oUEdSMGg2MDVwVDZXWDZxcXJGN0hOZ0plc3Q1TFh2SUtJZTN4NE45TVZvR0dMOVZzUW4zS1JXaTFyMmJmYmZOaVZ3ZHdSY0dDbzJCVkV6clYyRE9pRExaeDlGbDU1QmQzS0UzQ0ZobU5sR3BLNkVhNFV0b21NTmNSb0dIZWJXMlBUeGVvdVlXNXpHdDY1S0J1cFZkSS1DR1ZCRUt3UlJlYmNEc0R2Rkg1Y0NGdDJRcEswWWx5c0xOdUJib2FrWjZ4WlVRTE42Z2pYUzFYcFdHcEtxMnFhdElsWkNTcHZ4UnJHQzBSWm44aVNlLU4wNl83RFNHNU5PZFFMeTdGNWxRPT0=)
        track: internal
        in_app_update_priority: 0
  android-staging:
    name: Android Staging
    max_build_duration: 30
    environment:
      vars:
        ANDROID_KEYS_SECRET_PASSPHRASE: Encrypted(Z0FBQUFBQmloT05KY3Rsa2ZibHhKd2ZQQlp2Uk5UajdtNG9vSXZTZl9TLXp5OU12RklRMUpOZ1paR2dUWGczTFFhazNoNnZNRXktUFZCR0x4Y2NXcE9PUE12eWh5TVhxbk93bUFXVml1Tno2ZXFiRGRaaTRBMGc9)
      flutter: 2.10.5
      xcode: latest
      cocoapods: default
    cache:
      cache_paths:
        - $HOME/.gradle/caches
        - $FLUTTER_ROOT/.pub-cache
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: staging
          include: true
          source: true
      tag_patterns:
        - pattern: '*'
          include: true
    scripts:
      - brew install gnupg
      - sh $FCI_BUILD_DIR/scripts/decrypt_android_signing.sh  
      - |
        # set up local properties
        echo "flutter.sdk=$HOME/programs/flutter" > "$FCI_BUILD_DIR/android/local.properties"
      - flutter packages pub get
      - flutter build apk --release --flavor staging -t lib/main_staging.dart
    artifacts:
      - build/**/outputs/apk/**/*.apk
      - build/**/outputs/bundle/**/*.aab
      - build/**/outputs/**/mapping.txt
      - '*.snap'
      - build/windows/**/*.msix
      - flutter_drive.log
    publishing:
      slack:
        channel: '#codemagic-pipeline'
        notify_on_build_start: false
      firebase:
        firebase_token: Encrypted(Z0FBQUFBQmloTW1JeE1WZUFHQzNKWjFkUTZqS1JycHQxa053M3lsckc3QlExcFA0X056VnVGekcyV1VKbURLYVpLSUgwR1dNaENFZ2l1eVFuQVNnQ2R6OUZuY3BiQ0RzMlhjZjlTUmx0enJibzI5c05iTHR4cVg5QkM0VkhHclpNcm1qZmJDRlM3cjNDaFpKdlBCQnNZWTlZVFNGanFKT3AtVVpYSDJwZUJQSGVGOHMxcDM5UmZNVlpkYkpDZV9zWlBvcDV0d3ZBYXp6V2p1cTkyV0RlSjEybGRZamdpdXlvdz09)
        android:
          app_id: 1:899655281519:android:e5417a5437e18a0e77569a
          groups:
            - android
