definitions:
  - &melos-setup 
    name: init melos
    script: |
        #!/usr/bin/env sh
        set -e
        set -x
        cd /Users/builder/clone
        brew install dart
        dart pub global activate melos
        export PATH="$PATH":"$HOME/.pub-cache/bin"
        melos bs

workflows:
  pickup-staging-ios-workflow:
    name: Pickup Staging iOS Workflow
    max_build_duration: 30
    environment:
      vars:
        APP_STORE_CONNECT_ISSUER_ID: de4a206c-7100-496e-83a5-73e673af6c85
        APP_STORE_CONNECT_KEY_IDENTIFIER: 647N3684PB
        APP_STORE_CONNECT_PRIVATE_KEY: Encrypted(Z0FBQUFBQmhnNThFU3pqNHhsMjN0dWo3bnEteFZfU0ViT3lxTndETDhWS0FKX3ZtTGVtdlJVX19jaHc2T1hDMHNkVHpTVkR6NTNFM3BKSjBCaThYWFBZYjFqZXlaOWluXzU2T3doSm9ZcG1YcURRb2E5cS1MRnl2c3M3UU9oeHphRWFRZ1lQRUltbGt2YnJvTkkwTE9ncjVUdHFNR19DU0pOdFFFOUhya3hpVTVsTzVwdHJjRjg4N2lLTWdjdDZrZ2JMVlYweVg4Z2xUcFZWaUhPNGJtSjI2YlZWR21IZmNzaGZBZVozY2dUSVJtRGVOdndNZGxHT25kdS02UXZ6WkpvYndReWUtdm5UdWJlR1ZOYzBXQmFpcXEtZDVMNmc2MnZhOUJRUWhjN0ZrdmlkRDRfMmJRNmgwNlVveFV6WWgxU005Z2JKV3NVejZWZlNLc3hneXRmeVJfTEFMeExzcm1rTDhiTHYtV2s0SndWT0gtS2E5clptTUhxWk52eWRMMm1tQUlESmRSeXFaTVJMaFZ0ZHdTWHlTZUwtc2J5RlhsNEJOZlNvY1NSY3pRd3JtZGJkbHg2ST0=)
        CERTIFICATE_PRIVATE_KEY: Encrypted(Z0FBQUFBQmhnNThFc1BBVTdKODhvMWFJX2pwX0NicXRsc3FPSmlUb3M2Rk54VTZ0SUIzR0pKaUVBRzlhTENoNTdHdFFFYTRNbTNPMXdHeEZSWGFzUHU1MWdfOTIyOFFLQUV5UXBIc1FpQ1hXQnFZeWVDNzlYblJsOUdHNmdBUGRVcmMyUHRRRjFHTzdEREtjZkY3RF9IdWZNWjJHR0RyUmxBcVFMY1hfVDh5X3BQUkMtaHh0dzU2RHQ3OXhnYV82RXlnQWZzWXQ4dHFPcXRJOFhqQmtHYTAwbndDWDlOdVR2YVBsS1J2OG83TExBM184c2RObzNxbEN1UVpNT21MamZnYUJPZUVTdnV2NEQxaVktNzdwVDdKVktVNEltNWxRTElOMGNNYlpHbmlVS1JFRWdneUl4NUhOTVpXUl90dW54N1pzUEZNTENWQWZJVTNiTlJtSnVxUXc2N2JwWVRIZnNMazU4WW51Tm1UdVpTQlhaVUVBRHFJSEdPY3FrS0ZMRXY4dDJhZzVVNWd2ejlRYVFUOThINHlodVhUdkQteHVNQVFkSVlGWVF0b2k3cXNPeTYySFdYUDctWVZVX0RXczBlUi00ZUw1ZUtkQTRBNE5xTmhNam1NdUdZVUlwNTJUR2FWZlFCYzFoTHhMY1lqeGQ5TEppY3pGNjNkUDNuMmtGWmNucmpSTV9idnEwbjZPQW8zRG9wc1c1QVhGWlZyVDVDWENCX2Q0ai0weGltUjV0dE1POEc1bmpHUXNHUTVDbG1OYWctWFgwQUpVVDNSMzVIVzBWWENUMFpiOV9KZE43X0lPbUNrNFJvNHZycjlHSmE5XzlWMENoTlhwT2d2YUEtQTV1MlM0ZURPSTc1aUVMZHFvUGZEMEpFTmhFUExHWDBZdVpCZ1dIQ1BJWUc5dm9qRndPMDR6cGY1U0VVSG1vWHRIQlc4YzVUZ0FibWtxa2R2V3NEZG41VUlQcWMzcDREY1AxUkxDVGtsN1FUZjRSV3k5bUQ5LXJwZ2NXaHQ0ZHZMMXBGQm5DNlY3TUYtSUs4RmJpR3BUY29MOGR2RUJ4VGpjWmhUNXpBTUd2TzF6NkVNekhjd3NTZkJDNnBuaDNFZklhREhaVW5ReTI4ZWt0Um4xX2lkaHp6LUFoSEJlMDBHbWFiU2V1QVRBb2IxbWVTSDNlQ2QyUFpqMy1KV1o0ODJRU2d1aUFHMEtwb1RycDBFclZ3UF9BMGZ1QUNXQV9HNVpQN1dRcHV5NEU3MzdyYnVNTHVNc3RfV3hiTF8wVGJlNU9WNzNUeklBR2dmS0FhTEtUUEJfNTZCTnlmN2duRFFaRzZmd2ZNbXRsdWJ2cUV0dFYyUWhTejk1NkVSVlJuT0M0Q1ljWGR4MGdrTFFSNkxFdzNNQWhwWmo0OFVGZ3k5UmdUb1d5am9kVkF3Qmp3OXBqbXVCRlAwVmZoVFYyb05yQ0U4WS1COUNVUGxjX3RhcGQ1RlVJdDhsSEFXR0hmZm0zR3E0aXlFUHhDLU5hY3Bjai1xS01iZXVZYWRDTDJtYy1xZldwaTF5V1BNNU9hdlpPclA5ZC00TTJmb2NDNHBRS3dlWmlsZ0ZxM3VCUUNaX3RvRXBKU1hIR2J5S3B0REUxeTJUZUt0T19xUXNsMngxdjd3UEJlVHFKV3VRc05RS1puMmZoYU4xbHJObTJJeGREbkdRek1RSlZqczMtZ0s1em1FWTExTENNYndGMmc1dkRQVjRlalJLZ2tzWEJFWGk2R2tWNVJEb0pYZ1pCdUZBUTZ4bXItTGRFSG9lZnhsNEI1NjB5c3BLR2NzWHlYQzFnZlVJWnIzZ3NFOEFIVERaVGoyeWN3ZWpOMnFPd3ZUUmdBUUtBUlY4NktYQzVGVWh3aEs5bC1teFFyRmg2UTZYVUlmN3pOWGt4dVR3RTM5VzFVMXQ2T3hJR2FRVDhsR2p4bm5RSXo5OEVENFloZkVscDZDUVdNRnNQRDVwRndmdWx3c2xzQXpDbV9sRUV3ZmtYWlROUzZSTGdURkFTRTVxY2JabFNGXzZVY29DVEpucmNwNW4xejV2dWFNN2ZyWXkxOU05NmFqR29LYTF0MGJENFl2Wk5WcVVPcHFBVzIxUmlSVUxiX3dkS0pGZEt1aUFxWFl4Q0Y0ODFvTEtaOHNvMlY3Q0pXa0tEYzNOU1JHcUR2ZGlzN19URlVnTnh4ZzZ5OUNMOUtMaVA3TjRjdFFpWHc2aE1NTE5wQkhXdEFya2NhMDVwWktEOXVSZjM1V0lzZm83aGZJOFliNWFWa3VJdEpDLUg3SHN5WEVqTW1MUHoxV0J4Y2dCOTBFZVdpM09mSU9aY0JYWkFoZDAwcFhZd1VSUUtUUjFzZHA4M2xTY3pSUEZneVlXdEE2bnVmU1dqbFY4WWxZXzFNNE5ZQW42cThBOS1fMllWMXR0c3htYU1YMVlLSEEyLXNQcm9vOW15dUl3RkF0dzgxV29aU3R4VzI0Z19NTzJjQ3ZMRFFPUlcwZ0FrRmNhaWF3YWJ0QW41clhpWTNZbEdCa1hCelNoUWVtVlpQSjRUWjNHN1gzWHdCT0dsY1lHbTVTb3pERk5OZGpXb2tURklrb3NRdjRyUU5XWm9RcWFuUXpkckhRNHlSYXJFSWVpY0VDYVl5OFBtQ3lfRGpVTkY3VFk3Q00zNnZqRlh2UkdrZUZxdEV1OGV4alFldFVLZUVJYmxpZFpNbkF6RDlJaVRrNDl4Rm5yUVprd2Z2RTRKUGtzc0k3NDdUZ1ZxbV9rMTV0ZVpvQTFDU2pteGMtVVJxSmVVMnFNcEZ1WEM1TW5BdF8wVDRFU0ZtMnYzaGlnYlJ2bnRNMHVuN1dXNC1XZFJxRlppSGo3Uy04ZHJnRnRid1hLWDd1aVd1eVhCYUdRVzVWNE8tSGxyUV9ERUx0bGk1MjdnRXZVdllKUFVVdHZma2ZPWE1oQTJ2dWc2YjVBb3c3cmVZNWVHMENQQURjRmJnejRfV1lnODhNZlhxc0RFMmVpdkZwVWh1Z3pWXzVwRWtmZ1M0aE1hX0dyOTNGZm5obzlEdkZuMko5VWEtX09zQjRhdU1GRTE3Z2Q4R2RE)
      flutter: stable
      xcode: latest
      cocoapods: default
    triggering:
      events:
        - push
      branch_patterns: 
        - pattern: staging
      cancel_previous_builds: true
    when:
      changeset:
        includes:
          - 'apps/pickup'
    cache:
      cache_paths:
        - $HOME/Library/Caches/CocoaPods
        - $FLUTTER_ROOT/.pub-cache
    scripts:
      - *melos-setup
      - keychain initialize
      - app-store-connect fetch-signing-files "tech.getcrunch.crunch" --type IOS_APP_STORE
        --create
      - keychain add-certificates
      - xcode-project use-profiles
      - cd apps/pickup && flutter build ipa --export-options-plist=/Users/builder/export_options.plist
    artifacts:
      - apps/pickup/build/ios/ipa/*.ipa
    publishing:
      email:
        recipients:
          - joel.rose@code.berlin
          - crunchapp2021@gmail.com
      app_store_connect:
        api_key: Encrypted(Z0FBQUFBQmhnNThFd2U0Z2kxZnhuQ08yMUNmbEM4LVJmcTY2TUhLNU04NThTdWg0bzJMcnVrWGdCX2tyVWxSOWVaOERaVURNYk5ER0VyZ0otSVZKczNleHFYWEZXSjREU3N0Q2xycXNlWTNIR0o3bFo3NTMtLXQtal9HU0NNekdQQXpyRTNJWkpEQXYtRXJva3hpcnc2WEJlU3RJRG5mdjk2NW5hZWJvWjRXSmlGSGxkMkFiZmhNeGtUZlJpUHI2TnBqQmIzU0FEZkctZ0RqMjRsdXVUUkdWQ0VUV0tJQjdxYURpZ0dFNUE2MDhLRm1VOWRfTFRjSk5iV2kwalhBTGVsdGQ1TFBRcEhEZ0NFRGxrYVFMU0x0TEdvS1BDQ1RJNTJkdzJiSGY5dWxvLTVicXd0dFgwM0ZEeUFiS05FdWpNTnExMi1aV3Z4UjVjd2p4X1AzWktCOVZaR3NGVXJIb3owMDdSSjk1ckp3RmRkZEJIU0V2QWtDTjZycTdaajRSMVMxOEZXeTZrYW9DTXJDZzVtc3BCVTYtYThsUWJmRHVBaFZwaEZ4UF94UGFCTGxGcTZkZzItND0=)
        key_id: 647N3684PB
        issuer_id: de4a206c-7100-496e-83a5-73e673af6c85
        submit_to_testflight: true
