definitions:
  - &melos-setup 
    name: init melos
    script: |
        #!/usr/bin/env sh
        set -e
        set -x
        cd /Users/builder/clone
        HOMEBREW_NO_AUTO_UPDATE=1 brew install dart
        dart pub global activate melos
        export PATH="$PATH":"$HOME/.pub-cache/bin"
        melos bs

workflows:
  pickup-staging-ios-workflow:
    name: Pickup Staging iOS Workflow
    max_build_duration: 30
    environment:
      vars:
        APP_STORE_CONNECT_ISSUER_ID: de4a206c-7100-496e-83a5-73e673af6c85
        APP_STORE_CONNECT_KEY_IDENTIFIER: 647N3684PB
        APP_STORE_CONNECT_PRIVATE_KEY: Encrypted(Z0FBQUFBQmhnNThFU3pqNHhsMjN0dWo3bnEteFZfU0ViT3lxTndETDhWS0FKX3ZtTGVtdlJVX19jaHc2T1hDMHNkVHpTVkR6NTNFM3BKSjBCaThYWFBZYjFqZXlaOWluXzU2T3doSm9ZcG1YcURRb2E5cS1MRnl2c3M3UU9oeHphRWFRZ1lQRUltbGt2YnJvTkkwTE9ncjVUdHFNR19DU0pOdFFFOUhya3hpVTVsTzVwdHJjRjg4N2lLTWdjdDZrZ2JMVlYweVg4Z2xUcFZWaUhPNGJtSjI2YlZWR21IZmNzaGZBZVozY2dUSVJtRGVOdndNZGxHT25kdS02UXZ6WkpvYndReWUtdm5UdWJlR1ZOYzBXQmFpcXEtZDVMNmc2MnZhOUJRUWhjN0ZrdmlkRDRfMmJRNmgwNlVveFV6WWgxU005Z2JKV3NVejZWZlNLc3hneXRmeVJfTEFMeExzcm1rTDhiTHYtV2s0SndWT0gtS2E5clptTUhxWk52eWRMMm1tQUlESmRSeXFaTVJMaFZ0ZHdTWHlTZUwtc2J5RlhsNEJOZlNvY1NSY3pRd3JtZGJkbHg2ST0=)
        CERTIFICATE_PRIVATE_KEY: Encrypted(Z0FBQUFBQmhnNThFc1BBVTdKODhvMWFJX2pwX0NicXRsc3FPSmlUb3M2Rk54VTZ0SUIzR0pKaUVBRzlhTENoNTdHdFFFYTRNbTNPMXdHeEZSWGFzUHU1MWdfOTIyOFFLQUV5UXBIc1FpQ1hXQnFZeWVDNzlYblJsOUdHNmdBUGRVcmMyUHRRRjFHTzdEREtjZkY3RF9IdWZNWjJHR0RyUmxBcVFMY1hfVDh5X3BQUkMtaHh0dzU2RHQ3OXhnYV82RXlnQWZzWXQ4dHFPcXRJOFhqQmtHYTAwbndDWDlOdVR2YVBsS1J2OG83TExBM184c2RObzNxbEN1UVpNT21MamZnYUJPZUVTdnV2NEQxaVktNzdwVDdKVktVNEltNWxRTElOMGNNYlpHbmlVS1JFRWdneUl4NUhOTVpXUl90dW54N1pzUEZNTENWQWZJVTNiTlJtSnVxUXc2N2JwWVRIZnNMazU4WW51Tm1UdVpTQlhaVUVBRHFJSEdPY3FrS0ZMRXY4dDJhZzVVNWd2ejlRYVFUOThINHlodVhUdkQteHVNQVFkSVlGWVF0b2k3cXNPeTYySFdYUDctWVZVX0RXczBlUi00ZUw1ZUtkQTRBNE5xTmhNam1NdUdZVUlwNTJUR2FWZlFCYzFoTHhMY1lqeGQ5TEppY3pGNjNkUDNuMmtGWmNucmpSTV9idnEwbjZPQW8zRG9wc1c1QVhGWlZyVDVDWENCX2Q0ai0weGltUjV0dE1POEc1bmpHUXNHUTVDbG1OYWctWFgwQUpVVDNSMzVIVzBWWENUMFpiOV9KZE43X0lPbUNrNFJvNHZycjlHSmE5XzlWMENoTlhwT2d2YUEtQTV1MlM0ZURPSTc1aUVMZHFvUGZEMEpFTmhFUExHWDBZdVpCZ1dIQ1BJWUc5dm9qRndPMDR6cGY1U0VVSG1vWHRIQlc4YzVUZ0FibWtxa2R2V3NEZG41VUlQcWMzcDREY1AxUkxDVGtsN1FUZjRSV3k5bUQ5LXJwZ2NXaHQ0ZHZMMXBGQm5DNlY3TUYtSUs4RmJpR3BUY29MOGR2RUJ4VGpjWmhUNXpBTUd2TzF6NkVNekhjd3NTZkJDNnBuaDNFZklhREhaVW5ReTI4ZWt0Um4xX2lkaHp6LUFoSEJlMDBHbWFiU2V1QVRBb2IxbWVTSDNlQ2QyUFpqMy1KV1o0ODJRU2d1aUFHMEtwb1RycDBFclZ3UF9BMGZ1QUNXQV9HNVpQN1dRcHV5NEU3MzdyYnVNTHVNc3RfV3hiTF8wVGJlNU9WNzNUeklBR2dmS0FhTEtUUEJfNTZCTnlmN2duRFFaRzZmd2ZNbXRsdWJ2cUV0dFYyUWhTejk1NkVSVlJuT0M0Q1ljWGR4MGdrTFFSNkxFdzNNQWhwWmo0OFVGZ3k5UmdUb1d5am9kVkF3Qmp3OXBqbXVCRlAwVmZoVFYyb05yQ0U4WS1COUNVUGxjX3RhcGQ1RlVJdDhsSEFXR0hmZm0zR3E0aXlFUHhDLU5hY3Bjai1xS01iZXVZYWRDTDJtYy1xZldwaTF5V1BNNU9hdlpPclA5ZC00TTJmb2NDNHBRS3dlWmlsZ0ZxM3VCUUNaX3RvRXBKU1hIR2J5S3B0REUxeTJUZUt0T19xUXNsMngxdjd3UEJlVHFKV3VRc05RS1puMmZoYU4xbHJObTJJeGREbkdRek1RSlZqczMtZ0s1em1FWTExTENNYndGMmc1dkRQVjRlalJLZ2tzWEJFWGk2R2tWNVJEb0pYZ1pCdUZBUTZ4bXItTGRFSG9lZnhsNEI1NjB5c3BLR2NzWHlYQzFnZlVJWnIzZ3NFOEFIVERaVGoyeWN3ZWpOMnFPd3ZUUmdBUUtBUlY4NktYQzVGVWh3aEs5bC1teFFyRmg2UTZYVUlmN3pOWGt4dVR3RTM5VzFVMXQ2T3hJR2FRVDhsR2p4bm5RSXo5OEVENFloZkVscDZDUVdNRnNQRDVwRndmdWx3c2xzQXpDbV9sRUV3ZmtYWlROUzZSTGdURkFTRTVxY2JabFNGXzZVY29DVEpucmNwNW4xejV2dWFNN2ZyWXkxOU05NmFqR29LYTF0MGJENFl2Wk5WcVVPcHFBVzIxUmlSVUxiX3dkS0pGZEt1aUFxWFl4Q0Y0ODFvTEtaOHNvMlY3Q0pXa0tEYzNOU1JHcUR2ZGlzN19URlVnTnh4ZzZ5OUNMOUtMaVA3TjRjdFFpWHc2aE1NTE5wQkhXdEFya2NhMDVwWktEOXVSZjM1V0lzZm83aGZJOFliNWFWa3VJdEpDLUg3SHN5WEVqTW1MUHoxV0J4Y2dCOTBFZVdpM09mSU9aY0JYWkFoZDAwcFhZd1VSUUtUUjFzZHA4M2xTY3pSUEZneVlXdEE2bnVmU1dqbFY4WWxZXzFNNE5ZQW42cThBOS1fMllWMXR0c3htYU1YMVlLSEEyLXNQcm9vOW15dUl3RkF0dzgxV29aU3R4VzI0Z19NTzJjQ3ZMRFFPUlcwZ0FrRmNhaWF3YWJ0QW41clhpWTNZbEdCa1hCelNoUWVtVlpQSjRUWjNHN1gzWHdCT0dsY1lHbTVTb3pERk5OZGpXb2tURklrb3NRdjRyUU5XWm9RcWFuUXpkckhRNHlSYXJFSWVpY0VDYVl5OFBtQ3lfRGpVTkY3VFk3Q00zNnZqRlh2UkdrZUZxdEV1OGV4alFldFVLZUVJYmxpZFpNbkF6RDlJaVRrNDl4Rm5yUVprd2Z2RTRKUGtzc0k3NDdUZ1ZxbV9rMTV0ZVpvQTFDU2pteGMtVVJxSmVVMnFNcEZ1WEM1TW5BdF8wVDRFU0ZtMnYzaGlnYlJ2bnRNMHVuN1dXNC1XZFJxRlppSGo3Uy04ZHJnRnRid1hLWDd1aVd1eVhCYUdRVzVWNE8tSGxyUV9ERUx0bGk1MjdnRXZVdllKUFVVdHZma2ZPWE1oQTJ2dWc2YjVBb3c3cmVZNWVHMENQQURjRmJnejRfV1lnODhNZlhxc0RFMmVpdkZwVWh1Z3pWXzVwRWtmZ1M0aE1hX0dyOTNGZm5obzlEdkZuMko5VWEtX09zQjRhdU1GRTE3Z2Q4R2RE)
      flutter: stable
      xcode: latest
      cocoapods: default
    triggering:
      events:
        - push
      branch_patterns: 
        - pattern: staging
      cancel_previous_builds: true
    when:
      changeset:
        includes:
          - 'apps/pickup'
    cache:
      cache_paths:
        - $HOME/Library/Caches/CocoaPods
        - $FLUTTER_ROOT/.pub-cache
    scripts:
      - *melos-setup
      - keychain initialize
      - app-store-connect fetch-signing-files "tech.getcrunch.crunch" --type IOS_APP_STORE
        --create
      - keychain add-certificates
      - xcode-project use-profiles
      - cd apps/pickup && flutter build ipa --export-options-plist=/Users/builder/export_options.plist
    artifacts:
      - apps/pickup/build/ios/ipa/*.ipa
    publishing:
      email:
        recipients:
          - joel.rose@code.berlin
      app_store_connect:
        api_key: Encrypted(Z0FBQUFBQmhnNThFd2U0Z2kxZnhuQ08yMUNmbEM4LVJmcTY2TUhLNU04NThTdWg0bzJMcnVrWGdCX2tyVWxSOWVaOERaVURNYk5ER0VyZ0otSVZKczNleHFYWEZXSjREU3N0Q2xycXNlWTNIR0o3bFo3NTMtLXQtal9HU0NNekdQQXpyRTNJWkpEQXYtRXJva3hpcnc2WEJlU3RJRG5mdjk2NW5hZWJvWjRXSmlGSGxkMkFiZmhNeGtUZlJpUHI2TnBqQmIzU0FEZkctZ0RqMjRsdXVUUkdWQ0VUV0tJQjdxYURpZ0dFNUE2MDhLRm1VOWRfTFRjSk5iV2kwalhBTGVsdGQ1TFBRcEhEZ0NFRGxrYVFMU0x0TEdvS1BDQ1RJNTJkdzJiSGY5dWxvLTVicXd0dFgwM0ZEeUFiS05FdWpNTnExMi1aV3Z4UjVjd2p4X1AzWktCOVZaR3NGVXJIb3owMDdSSjk1ckp3RmRkZEJIU0V2QWtDTjZycTdaajRSMVMxOEZXeTZrYW9DTXJDZzVtc3BCVTYtYThsUWJmRHVBaFZwaEZ4UF94UGFCTGxGcTZkZzItND0=)
        key_id: 647N3684PB
        issuer_id: de4a206c-7100-496e-83a5-73e673af6c85
        submit_to_testflight: false

  vendor-staging-ios-workflow:
    name: Vendor Staging iOS Workflow
    max_build_duration: 30
    environment:
      vars:
        APP_STORE_CONNECT_ISSUER_ID: de4a206c-7100-496e-83a5-73e673af6c85
        APP_STORE_CONNECT_KEY_IDENTIFIER: 647N3684PB
        APP_STORE_CONNECT_PRIVATE_KEY: Encrypted(Z0FBQUFBQmhnLWtqaDFtaGtJV1lZTXRlSnpKa3FFQ0RoWUt4OWx3STdwTTdIc1lyZVd5Z21XUXExZnFubTBkQ2I0T1JqQVNrbTlvaGV6bFhtVGZ2RmRNcW91WEhQRmppVWVWby1UUFF2bVNWLWJQR1hKQTlmUEYxVXNQSWlOajZlbnFGYzh1a2tGY2Rfam9zQmlTek1lT1R1UnVUS1I1cXAtLVpPOVNxSlhza0gwa0NiWHNMT2QtWkdMcmx0WHZJOTIya0tieTVVbThlSEhtYWpHOXNMQVEySDV3LW91cFFadFVFazFRVjhHVU1tbFFsSUFqbjF1NlZQZjQxVzBfWF94dVVmUUd3VUxUZFhoYkRtc0pGRGFiZUVEU2I1Q3RLVzczdnl6cVZ3RzJEOVRDdjRoMVgxWFFsM2xpbjh1NlRjVXhEaHF1d09PbVRWdnlFbl9pY1dtaTNvb0tNT005OXlOcXdUN0o0aHMwVE9yeHJ5LTUwSmtUZ3FTWjFtSWtudkRTUC03SVVYV2xNVHpPZzFvZF92TGQ2eF9YcXNMRnNpZWtOU2U5dXB4ZDZjcE4zMkl3aDdPUT0=)
        CERTIFICATE_PRIVATE_KEY: Encrypted(Z0FBQUFBQmhnLWtqOHF4X2NNNHpnZ0k1dFhBTW80X0hfWmYtTC1DR0R3Wk1tX0piNER0RlUxclRISUxBenZBRVhqNlNnX2RvUFBtTm9qUGdGdGdraEdnSXlUTVUwMmZ5X3ZxUjJGRXBxNzdaR0NGQzZ5dlktS0RuY3NMeTVDM0JpUG5uQi1GMzloeHk0eUtqTmNYMnliQk1LOVc3YW15MWhSSVJJM1BqVTR2aUtLZ3RiWDhOTTNjNzlKZm9vamxoMDMxQWFZVFZyZWtKRW5iYTg2T0UwbVRzMzdaRzhlTXJKS0c2YUpuTnFSMkJIRDFjRUI4V0QwWU5NOF91SElDbThfbkttNjhnbHZmV2x5N0J3VmRSMXdJbFVjWHktaUhiZl95WWhGMmhvT3J4LUtReEZmVjFTX3M2dVlHSW0wR1BweHB6VkMzZWcyWHdXUS04V1ZwRG9STU1HU2V3SlIwRDNpWmlXZ3NJdUI5djNIaUx3NnZ5cWZaZFVnQTBIeWU4Q3FPdkQ1R3hMSGM4RnZBWHZaQk5od05jeFM1X044ZHlXV0sxWWZXdE82ekJfWFJvVElQS2lKaXNhS1V2dkNYODBON3NXTWNwRVY5NkJSMWdQYXVqTEpNS2xIek5zaGdVVW9Td1JwWXFmSTF5eGRkTzVhdThmSWtVMDZ6TWZzQVZLbjJ4NDVWdzJranY0SjFBWU1oLTNwTHZwVWdfTXM4aF9rUGNoa1V2Y2Z2d0pSWlh0TEhPVURJVkVoM2dNejUwU3hxcHBUOHdXQldRVWRwVGlOSU1mOFRKa29COTZWNnFBaEFHSWZ6cHhnZVQzNWZxSlVTYzFCeklRNWxoSWxsY0hFY2VBV1lPRFV6NWZ3ZjZ3eS15NklfR2FYUkRCMlVVZ2lXdDB2MmU4c0VhRDBNZjJjdHJDYnBiRy1jVDJHdkxtNmNGanlJS092XzlZdmE3M3R5d3VnelBjRzJ5ZEllRm0wNlIwaTB5MjlRNEg2VDBMc3NBMjJTM2tWZjY1WUw2Z3dhUWptYjJoTk4taEkzWmJUNzNGUnExVUxLUENhSWVQenQzUm1scHRiVk5MSWVZY3RnQUdyckVqTGlySHpqdnNyQ0pUSHFFZy00VUtJZGM0dTZvNVdOWDBEdlN3Ty0yTHRNbzNFN25uRFpOQTZDcTlsajZIdmZxcUhyWENZcVVaZVpkbnZ1SE1xcUp0WjlOUW5uQjRzVWd2ckJKZ0lZM0xqUDROc1JjQi0zOVphekpLc19ISjJUWjg1amlUX2l4cWVFbGNzWXRrbFFael93R0k1cFNCbGxSU2pfXzY3QUxhSE5KcGV2V2lCRW4yaWRUbEhJaklUd0xpdDM2TGxNT3NldUt4UDM1NVJNNUJhSFVBU1BVU3hWMEpneWtVU3g5elprRFVDci05SjZRaHpuZi1keEdjajZybjk1dnRidmVxbWVrN21ZeWZ4dUZWLWNNNDZFXzZYNFd2aTZfQXdrWUlxcmhTVnI3Mm1qY1QxNkJmeldTSEdzQzhDYjJtbFR2R1pPblFGWkM3Ti16NnJIWmNSR0x0clhvMUtfZjBwc2dUVzRKbU0tVEcxMDFlY3pVd2V4RzlkZFI4dGozQXBvUnRETTZMZGNuNVpfRmtuLTM4T3p6a3JCS3FOcVExSGQ3c0ZhRjhtTnVpUUR0dUVqVTNFTGFDZFZvdE9TUWRSZFhndTE4VU9fcFNXM0N6RW50bXczckV0Um5Oc19FMDlJaXVlLTJJSnd5dFlxRlpjU05CYWhsQ1JoU3I1QUpaaGN2R1F1c3hseUUxRDFNT1JqdWt4ejMzOTdrWllkZTNXRGJtODZwVEJueDZGSHplOHhJcDE2a0dJWl9GakhqS3AycGlON1BDWmdROEdzMHdNOGpNSkRVVVdkOFViZkZRR01UNC1SeUhybkVCd1hvX0JxaGo2YmVjTUwwdTJnNFJzMDhkUGFSODcxYWpva1FyU0hIUncyU2E2N09PMy1zSXI3dHNMOER2TDlYeUJ0dWUxcmhOR296MG0xUlFIRHc0Yk5uZUg4cGV4TE5HdVhCSV9IQ1c4ZWFhbC1lSnhjY3E5c0RSOFdFRC1nTGp1OEdYMVhGNl95TF9TVVVJYnM1c2lmdFlpVkN3cEFHc2I3VC1YaDNtci1Ka1JsVlZxbDNOaVRYbjVoenhTRS1fLUY2bEduRzYwMGttNnhReWVodDhudFh6MWVVNXFUMEhKZ2dKTEc2dXpqVEhQWmtKZEs4S1JRdUJmYTdyR1RZdkJMOE5wR2k0Z0FIaEI2SnBjeTkwRWFtZ2FaQklrRTdwZlczQzZfemdlamNYZ1c1cF9FSkJNajJJMFNRanhxM1FnNHNqUlJlcDJ1YVZJSVZGSmNyZHZCdjR0NVZhTl95NEhZTUZTZVdsdU4yYkdicGhyVmowek9UNXpYVE5RRjZ1RFYzU1RfLXRDdU9hTUhJWmhJcmV3cVFHWjJxNUFzdnJBR0tNVnJybXlmZ0ZtVF9hQWt5NnY4UWRIOEloVF9HYThwa0ZNYldIS3JKX0p2Q0JEWnpueXp4U0F3a29WWTdBcGpTQW9KVzJNV3JKdWpRaEZ4bVZEM19WdlhmRGpjMkVObVRhWk9ySV9iM3ppWGdrZld1VGNIaTlHc0k3ODl1ckQzZ0V4Zi1DWVFfcmI4ODNkMzdobkdCdUlKWjBDR0VpbHhUWWVIcDJCLW5PLWM1U21HMVFMRml2V0VfVHcxdWJJcmV1SUxmMzBVSUdieDc2dnBYUEFudHNDV3B4dTBSczBlbzdXdGdwZnFyOEUxV0Nib0czYmdjemhNSVFTTVIycVlfN0lGRF9OYVFuU3d6RjlxR1BERnRFbTJaUTQ1WUJsc2p4eUt6ZVpLRGxQaDFoWHMtaEM5bUoyNDAtR0l2OEtWdFU0dXNNUWlCOUVvTC1YTWh1MWFKN0lzMW81cTdSV2VFRlc0SUx0dUM5VERvSkVaZFc0bDhUYTJodDltMENrOEFxT3A0VW5YT19zTWhWQTBsbDdpVTU2NkJaVlgyMWkyRHBUaUdOelREVjN0eXg4bzNoQnB5dmFweF9Fc0ZBLVVo)
      flutter: stable
      xcode: latest
      cocoapods: default
    triggering:
      events:
        - push
      branch_patterns: 
        - pattern: staging
      cancel_previous_builds: true
    when:
      changeset:
        includes:
          - 'apps/vendor'
    cache:
      cache_paths:
        - $HOME/Library/Caches/CocoaPods
        - $FLUTTER_ROOT/.pub-cache
    scripts:
      - *melos-setup
      - keychain initialize
      - app-store-connect fetch-signing-files "tech.getcrunch.vendor" --type IOS_APP_STORE
        --create
      - keychain add-certificates
      - xcode-project use-profiles
      - flutter build ipa --export-options-plist=/Users/builder/export_options.plist
    artifacts:
      - apps/pickup/build/ios/ipa/*.ipa
    publishing:
      email:
        recipients:
          - joel.rose@code.berlin
      app_store_connect:
        api_key: Encrypted(Z0FBQUFBQmhnLWtqdjRKTDBZRVBCT0dZanF4SklIY2lGSXp0UjJxSGhONG10MzRCRzVtVkVuWTQxN1U2Vy03VENCZm13WTVyQ0tnSm1WREVURWhTY0l4ZXAtcmxxODBpeGZsTzJxZy1xOWJnZW1Na0YyaUFyTS1PMldrNlNaQkI1TC00NXVxVEN6VnhORGhHbTlmcWktRXFSQlU1VjVBaXZTbzhNa1l4OHNqcC0xUHpWQ250WlN0bXZzMnptdG9uYmsyRVF0cUJiSlNEaDE1UDhCQ19QUlVtNEhUUFU0bFdLa0VaajVVUGc5dE9qWkdTVll5ZHl2QjdhdWJPSVZrVEo1eTFGTHl6X2xjX3B3Znh5ZzdoX0pQdUZqNnE2S05FMEdVQlZ1MVJtN1B1bmFyNHRGdEhxZ1g4aWJvaDNjcnh0T2g0Nk9nUDdpX2pIdnJhYmM5MjRoZm96R2NUemNZSVVOSUZqY0FaX1VEX2pLMmRKNlRYVTdDbHg4b0FkNnNCNF95M01jeDdIZ1BTSHNWN0VOelNKTVNzcWM1Q0J0eTNYMFFoMmdUUDlHOFhCZW15UjAwSWpKUT0=)
        key_id: 647N3684PB
        issuer_id: de4a206c-7100-496e-83a5-73e673af6c85
        submit_to_testflight: false
