name: pickup
description: Crunch customer app

publish_to: 'none'

version: 1.0.0+1023

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  alpaca: 
    path: packages/alpaca
  app_outdated_repository: 
    path: packages/app_outdated_repository
  authentication_repository: 
    path: packages/authentication_repository
  cached_network_image: ^3.2.0
  checkout_repository: 
    path: packages/checkout_repository
  collection: ^1.15.0
  cupertino_icons: ^1.0.4
  custom_map_markers: ^0.0.2+1
  equatable: ^2.0.3
  firebase_analytics: ^9.1.6
  firebase_crashlytics: ^2.6.3
  fleasy: ^0.13.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  flutter_dotenv: ^5.0.2
  flutter_svg: ^1.0.3
  hermes_repository: 
    path: packages/hermes_repository
  intl: ^0.17.0
  loading_overlay_repository: 
    path: packages/loading_overlay_repository
  local_storage_checkout_api: 
    path: packages/local_storage_checkout_api
  material_floating_search_bar: ^0.3.7
  onesignal_repository: 
    path: packages/onesignal_repository
  package_info_plus: ^1.4.2
  phone_number: ^0.12.0+1
  pin_code_fields: ^7.4.0
  platform_maps_flutter: ^1.0.2
  skeleton_loader: ^2.0.0+4
  stripe_repository: 
    path: packages/stripe_repository
  url_launcher: ^6.1.0

dev_dependencies:
  bloc_test: ^9.0.3
  build_runner: ^2.1.10
  fake_async: ^1.2.0
  flutter_launcher_icons: ^0.9.2
  flutter_localizations:
    sdk: flutter  
  flutter_test:
    sdk: flutter
  lint: ^1.7.2
  mockingjay: ^0.3.0
  mocktail: ^0.3.0
  mocktail_image_network: ^0.3.0

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/
    - assets/onboarding/
    - assets/placeholder/
    - assets/logo/
    - assets/icons/
    - assets/enviroments/