name: pickup
description: Crunch customer app

publish_to: 'none'

version: 0.7.4+39

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  alpaca: 
    path: packages/alpaca
  authentication_repository: 
    path: packages/authentication_repository
  bloc: ^8.0.1
  cached_network_image: ^3.2.0
  collection: ^1.15.0
  cupertino_icons: ^1.0.4
  equatable: ^2.0.3
  firebase_analytics: ^9.1.0
  firebase_core: ^1.12.0
  firebase_crashlytics: ^2.5.1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  flutter_dotenv: ^5.0.2
  flutter_easyloading: ^3.0.3
  flutter_stripe: ^2.1.1
  flutter_svg: ^1.0.3
  hermes_repository: 
    path: packages/hermes_repository
  http: ^0.13.4
  intl: ^0.17.0
  material_floating_search_bar: ^0.3.4
  onesignal_repository: 
    path: packages/onesignal_repository
  phone_number: ^0.12.0+1
  pin_code_fields: ^7.3.0
  skeleton_loader: ^2.0.0+4
  url_launcher: ^6.0.12

dev_dependencies:
  bloc_test: ^9.0.3
  build_runner: ^2.1.7
  fake_async: ^1.2.0
  firebase_auth_mocks: ^0.8.2
  flutter_launcher_icons: "^0.9.2"
  flutter_localizations:
    sdk: flutter  
  flutter_test:
    sdk: flutter
  google_sign_in_mocks: ^0.2.1
  lint: ^1.7.2
  mockingjay: ^0.3.0
  mockito: ^5.1.0
  mocktail_image_network: ^0.3.0
  test: any

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/
    - assets/onboarding/
    - assets/placeholder/
    - assets/logo/
    - assets/icons/
    - assets/enviroments/
