name: pickup
description: Crunch customer app

publish_to: 'none'

version: 0.7.0+25

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  alpaca: 
    path: packages/alpaca
  bloc: ^8.0.1
  cached_network_image: ^3.2.0
  cupertino_icons: ^1.0.4
  easy_localization: ^3.0.0
  equatable: ^2.0.3
  firebase_analytics: ^9.1.0
  firebase_auth: ^3.3.6
  firebase_core: ^1.12.0
  firebase_crashlytics: ^2.5.1
  firebase_messaging: ^11.2.6
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  flutter_datetime_picker: ^1.5.1
  flutter_dotenv: ^5.0.2
  flutter_easyloading: ^3.0.3
  flutter_email_sender: ^5.0.2
  flutter_slidable: ^0.6.0
  flutter_stripe: ^2.1.1
  flutter_svg: ^1.0.3
  get_it: ^7.2.0
  google_sign_in: ^5.1.0
  hermes_api: 
    path: packages/hermes_api
  image_picker: ^0.8.4+2
  intl: ^0.17.0
  material_floating_search_bar: ^0.3.4
  onesignal_flutter: ^3.2.8
  pin_code_fields: ^7.3.0
  platform_maps_flutter: ^1.0.2
  provider: ^6.0.2
  rxdart: ^0.27.2
  sanity: 
    path: packages/sanity
  shared_preferences: ^2.0.11
  skeleton_loader: ^2.0.0+4
  stretchy_header: ^2.0.0
  the_apple_sign_in: ^1.1.1
  url_launcher: ^6.0.12

dev_dependencies:
  bloc_test: ^9.0.3
  build_runner: ^2.1.7
  firebase_auth_mocks: ^0.8.2
  flutter_launcher_icons: "^0.9.2"
  flutter_test:
    sdk: flutter
  google_sign_in_mocks: ^0.2.1
  lint: ^1.7.2
  mockito: ^5.1.0
  mocktail_image_network: ^0.3.0
  test: any

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/onboarding/
    - assets/placeholder/
    - assets/translations/
    - assets/logo/
    - assets/icons/
    - assets/enviroments/
