name: pickup
description: Crunch customer app

publish_to: 'none'

version: 0.1.1+16

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  alpaca: ^1.0.0
  cloud_firestore: ^2.4.0
  cloud_functions: ^3.0.3
  cupertino_icons: ^1.0.2
  easy_localization: ^3.0.0
  firebase_analytics: ^8.3.2
  firebase_auth: ^3.0.1
  firebase_core: ^1.4.0
  firebase_messaging: ^10.0.7
  flutter:
    sdk: flutter
  flutter_datetime_picker: ^1.5.1
  flutter_email_sender: ^5.0.2
  flutter_slidable: ^0.6.0
  flutter_stripe: ^1.3.0
  flutter_svg: ^0.22.0
  get_it: ^7.2.0
  google_fonts: ^2.1.0
  google_sign_in: ^5.1.0
  image_picker: ^0.8.4+2
  intl: ^0.17.0
  material_floating_search_bar: ^0.3.4
  pin_code_fields: ^7.3.0
  platform_maps_flutter: ^1.0.2
  provider: ^6.0.0
  rxdart: ^0.27.2
  sanity: ^1.0.0
  the_apple_sign_in: ^1.1.1
  url_launcher: ^6.0.12

dev_dependencies:
  flutter_launcher_icons: "^0.9.2"
  flutter_test:
    sdk: flutter
  lint: ^1.7.2
  mockito: ^5.0.16
  test: any

flutter_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: "assets/logo/crunch.png"

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/onboarding/
    - assets/placeholder/
    - assets/translations/
    - assets/logo/
    - assets/icons/
