name: authentication_repository
description: A dart package for the Authentication Implementaton

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  firebase_auth: ^3.3.6
  firebase_core: ^1.12.0
  firebase_crashlytics: ^2.5.1
  google_sign_in: ^5.1.0
  the_apple_sign_in: ^1.1.1