name: authentication_repository
description: A dart package for the Authentication Implementaton

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  firebase_auth: ^3.3.15
  firebase_core: ^1.15.0
  firebase_crashlytics: ^2.6.3
  google_sign_in: ^5.3.0
  the_apple_sign_in: ^1.1.1
dev_dependencies:
  firebase_auth_mocks: ^0.8.2
  flutter_test:
    sdk: flutter
  google_sign_in_mocks: ^0.2.1
  mocktail: ^0.3.0
