name: alpaca
description: Crunch Styling

publish_to: "none"

version: 1.0.0

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  cached_network_image: ^3.2.0
  flutter:
    sdk: flutter
  flutter_svg: ^1.0.3
  google_fonts: 2.2.0
