name: loading_overlay_repository
description: Repository for the Loading Overlay
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  alpaca: 
    path: ../alpaca
  flutter:
    sdk: flutter
  flutter_easyloading: ^3.0.3
  google_fonts: 2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
