name: Staging PR - Test

on:
  pull_request:
    branches:
      - 'staging'

jobs:
  flutter-test:
    name: Run flutter test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout project
        uses: actions/checkout@v2
      
      - name: Install flutter
        uses: subosito/flutter-action@v2.4.0
        with:
          flutter-version: '2.10.0'
          channel: 'stable'
    
      #- name: Format
      #  run: flutter format --set-exit-if-changed lib test

      #- name: Analyze
      #  run: flutter analyze lib test

      - name: Get Packages
        run: flutter pub get

      - name: Run tests
        run: flutter test --no-pub --coverage --test-randomize-ordering-seed random

      - name: Check Code Coverage
        uses: VeryGoodOpenSource/very_good_coverage@v1.1.1