name: Echo Code Coverage Number

on: push

jobs:
  code_coverage:
    name: Get Code Coverage
    runs-on: ubuntu-latest

    steps:
      - name: Checkout project
        uses: actions/checkout@v2
      
      - name: Install flutter
        uses: subosito/flutter-action@v1
        with:
          channel: 'stable'
      
      - name: Run flutter precache
        run: flutter precache
      
      - name : Install dependencies
        run: flutter pub get
      
      - name: Run flutter tests
        run: flutter test --coverage

      - name: Get Code Coverage
        uses: joelrose/code-coverage@v1
        with:
          path: ./coverage/lcov.info

      - name: Echo Code Coverage
        run: echo "${{ steps.code_coverage.outputs.code_coverage }}""
