name: stripe_repository
description: A package for our Stripe Integration

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  hermes_repository: 
    path: ../hermes_repository
  flutter:
    sdk: flutter
  flutter_stripe: ^5.1.0